<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Platform Condition=" '$(Platform)' == '' ">x86</Platform>
    <OutputType>WinExe</OutputType>
    <RootNamespace>PE_Tools</RootNamespace>
    <UseWindowsForms>true</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>tool-box_2276313.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="NLog" Version="6.0.6" />
    <PackageReference Include="System.Data.SqlClient" Version="4.9.0" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="10.0.0" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Views\DatabaseSettingsView.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Views\PowershellCommandsView.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Views\UserControlProjectSelector.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <EmbeddedResource Include="Properties\licenses.licx" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="tool-box_2276313.ico" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Resources\" />
  </ItemGroup>
</Project>