<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Platform Condition=" '$(Platform)' == '' ">x86</Platform>
    <OutputType>WinExe</OutputType>
    <RootNamespace>PE_Tools</RootNamespace>
    <UseWindowsForms>true</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>tool-box_2276313.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="DevExpress.BonusSkins.v21.2" />
    <Reference Include="DevExpress.Data.Desktop.v21.2" />
    <Reference Include="DevExpress.Data.v21.2" />
    <Reference Include="DevExpress.Utils.v21.2" />
    <Reference Include="DevExpress.Sparkline.v21.2.Core" />
    <Reference Include="DevExpress.XtraBars.v21.2, Version=21.2.6.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a, processorArchitecture=MSIL" />
    <Reference Include="DevExpress.XtraEditors.v21.2" />
    <Reference Include="DevExpress.Printing.v21.2.Core" />
    <Reference Include="System.Configuration" />
    <Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="Microsoft.CSharp" />
    <PackageReference Include="Microsoft.PowerShell.5.ReferenceAssemblies" Version="1.1.0" />
    <PackageReference Include="NLog" Version="6.0.6" />
    <PackageReference Include="System.Data.SqlClient" Version="4.9.0" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Views\DatabaseSettingsView.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Views\PowershellCommandsView.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Views\UserControlProjectSelector.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <EmbeddedResource Include="Properties\licenses.licx" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="tool-box_2276313.ico" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Resources\" />
  </ItemGroup>
</Project>